// Todo App - Generated by Nuero
let todos = JSON.parse(localStorage.getItem('todos')) || [];

// DOM Elements
const todoList = document.getElementById('todo-list');
const todoInput = document.getElementById('todo-input');
const addTodoBtn = document.getElementById('add-todo-btn');

// Initialize
addTodoBtn.addEventListener('click', addTodo);
todoInput.addEventListener('keypress', (e) => {
  if (e.key === 'Enter') addTodo();
});

// Add new todo
function addTodo() {
  const text = todoInput.value.trim();
  if (text) {
    todos.push({ text, completed: false });
    saveTodos();
    renderTodos();
    todoInput.value = '';
  }
}

// Handle clicks on todo list
todoList.addEventListener('click', (e) => {
  e.stopPropagation();
  
  const li = e.target.closest('li');
  if (!li) return;
  
  const index = parseInt(li.dataset.id, 10);
  
  if (e.target.classList.contains('remove-btn')) {
    // Delete todo
    todos.splice(index, 1);
  } else if (e.target.tagName !== 'BUTTON') {
    // Toggle complete (click on text, not button)
    todos[index].completed = !todos[index].completed;
  }
  
  saveTodos();
  renderTodos();
});

// Render all todos
function renderTodos() {
  todoList.innerHTML = todos.map((todo, index) => `
    <li class="todo-item ${todo.completed ? 'completed' : ''}">
      ${todo.text}
      <button class="remove-btn">Remove</button>
    </li>
  `).join('');
}

// Save to localStorage
function saveTodos() {
  localStorage.setItem('todos', JSON.stringify(todos));
}

// Initial render
renderTodos();
