"""Landing Page Builder - High-converting landing pages"""
from typing import Dict, Any
from dataclasses import dataclass

@dataclass
class Section:
    name: str
    code: str
    type: str

class LandingPageBuilder:
    def build(self, description: str) -> Dict[str, Any]:
        return {
            "index.html": self._generate_html(),
            "styles.css": self._generate_css()
        }
    
    def _generate_html(self) -> str:
        return '''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Landing Page</title><link rel="stylesheet" href="styles.css"></head><body><nav class="navbar"><div class="container"><a href="#" class="logo">Logo</a><div class="nav-links"><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#" class="btn btn-primary">Get Started</a></div></div></nav><section class="hero"><div class="container"><h1>Transform Your Business</h1><p>Streamline operations and boost productivity.</p><div class="hero-cta"><a href="#" class="btn btn-primary">Start Free Trial</a><a href="#" class="btn btn-outline">Learn More</a></div></div></section><section id="features" class="features"><div class="container"><h2>Features</h2><div class="feature-grid"><div class="feature-card"><h3>🚀 Fast</h3><p>Lightning quick</p></div><div class="feature-card"><h3>🔒 Secure</h3><p>Enterprise-grade</p></div><div class="feature-card"><h3>📊 Analytics</h3><p>Real-time insights</p></div></div></div></section><section id="pricing" class="pricing"><div class="container"><h2>Pricing</h2><div class="pricing-grid"><div class="pricing-card"><h3>Starter</h3><div class="price">$0/mo</div><ul><li>5 Users</li><li>10GB Storage</li></ul><a href="#" class="btn btn-secondary">Get Started</a></div><div class="pricing-card popular"><span class="badge">Popular</span><h3>Pro</h3><div class="price">$49/mo</div><ul><li>25 Users</li><li>100GB Storage</li></ul><a href="#" class="btn btn-primary">Get Started</a></div></div></div></section><footer class="footer"><div class="container"><p>© 2026 Company</p></div></footer><script src="main.js"></script></body></html>'''
    
    def _generate_css(self) -> str:
        return ''':root{--primary:#6366f1;--secondary:#a855f7;--dark:#0f172a;--light:#f8fafc;--gray:#64748b}*{margin:0;padding:0;box-sizing:border-box}body{font-family:Inter,-apple-system,sans-serif;color:var(--dark)}.container{max-width:1200px;margin:0 auto;padding:0 2rem}.btn{display:inline-block;padding:0.875rem 2rem;border-radius:0.5rem;font-weight:600;text-decoration:none;transition:all 0.3s ease;border:none;cursor:pointer}.btn-primary{background:linear-gradient(135deg,var(--primary),var(--secondary));color:white}.btn-primary:hover{transform:translateY(-2px);box-shadow:0 10px 30px rgba(99,102,241,0.3)}.btn-secondary{background:var(--light);color:var(--dark);border:2px solid var(--gray)}.navbar{position:fixed;top:0;left:0;right:0;background:rgba(255,255,255,0.95);backdrop-filter:blur(10px);padding:1rem 0;z-index:1000}.nav-content{display:flex;justify-content:space-between;align-items:center}.logo{font-size:1.5rem;font-weight:800;color:var(--primary);text-decoration:none}.nav-links{display:flex;align-items:center;gap:2rem}.nav-links a{text-decoration:none;color:var(--dark);font-weight:500}.hero{min-height:100vh;display:flex;align-items:center;padding:8rem 0 4rem;background:linear-gradient(135deg,#f8fafc,#e2e8f0)}.hero h1{font-size:3.5rem;margin-bottom:1rem;background:linear-gradient(135deg,var(--primary),var(--secondary));-webkit-background-clip:text;-webkit-text-fill-color:transparent}.hero p{font-size:1.25rem;color:var(--gray);margin-bottom:2rem}.hero-cta{display:flex;gap:1rem}.features{padding:6rem 0;background:white}.features h2{font-size:2.5rem;text-align:center;margin-bottom:3rem}.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2rem}.feature-card{padding:2rem;background:var(--light);border-radius:1rem;text-align:center;transition:all 0.3s ease}.feature-card:hover{transform:translateY(-5px)}.pricing{padding:6rem 0;background:var(--light)}.pricing h2{font-size:2.5rem;text-align:center;margin-bottom:3rem}.pricing-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2rem}.pricing-card{background:white;padding:2rem;border-radius:1rem;text-align:center;position:relative}.pricing-card.popular{border:2px solid var(--primary);transform:scale(1.05)}.badge{position:absolute;top:-12px;left:50%;transform:translateX(-50%);background:var(--primary);color:white;padding:0.25rem 1rem;border-radius:1rem;font-size:0.75rem}.price{font-size:3rem;font-weight:800;margin:1.5rem 0}.pricing-card ul{list-style:none;margin:2rem 0;text-align:left}.pricing-card li{padding:0.5rem 0;color:var(--gray)}.footer{background:var(--dark);color:white;padding:3rem 0;text-align:center}@media(max-width:768px){.feature-grid,.pricing-grid{grid-template-columns:1fr}.hero h1{font-size:2.5rem}.hero-cta{flex-direction:column}}'''

def build_landing_page(description: str) -> Dict[str, Any]:
    return LandingPageBuilder().build(description)
